### PR TITLE
Added type safety and square 1 algorithm. 

### PR DESCRIPTION
**Pull request by ianfrye0818**
Added type safety using a PuzzleType Enum and TypeScript. Can import scrambler and PuzzleTypes. Two methods are available on the scrambler class are generateScramble which takes in the puzzle type enum value. You also have a getScrambleTypes method which lists the available scramble types.

### CODE REVIEW

**Comment by jpatel2005** [comment]
Could you share some details/resources concerning your implementation for the square-1 scrambler? The notation that you're using doesn't seem to match the official notation.

I can accept your commit if you remove that scramble type, as I'm pretty certain that it was not implemented correctly.

**Comment by ianfrye0818** [comment]
Square 1 has been removed from scrambles.

**Comment by jpatel2005** [comment]
Looks good to me! Sorry for not saying it earlier for thanks for contributing. I really appreciate it!

**Comment by ianfrye0818** [comment]
You're welcome! Thanks to you for providing it in the first place.

**Pull request merged**
